### ISSUE TITLE
Add support to highlight block-local variable?

### ISSUE THREAD

**Issue by lukertty** [Lindydancer/ruby-extra-highlight#1]
It would be really nice if ruby-extra-highlight could add highlight to ruby block-local variable like:

```rb
create_table :sponsors do |t|                # highlight 't' in face1
    t.string :name, null: false              # highlight 't' in face2
end
```

Thank you!

**Comment by Lindydancer** [comment]
Hi!

I agree that it would be nice.

However, it would require a much more advanced parsing mechanism than what
currently is available, which I unfortunately haven't got time to develop
in the foreseeable future.

    -- Anders

**Comment by lukertty** [comment]
Emmm, maybe i will learn some elisp and try myself...

Thank you all the same!

**Comment by Lindydancer** [comment]
>
> Emmm, maybe i will learn some elisp and try myself...
>

Please do, Emacs a fun environment work in, as you get instant feedback in
terms of useful enhancements. I find this especially true when working with
syntax highlighting.

Good luck!

    -- Anders
